import {
  Archive,
  AtSign,
  Award,
  BookMarked,
  BookOpen,
  Brain,
  Calculator,
  CalendarDays,
  ClipboardList,
  Clock,
  Code2,
  Compass,
  FlaskConical,
  Flame,
  FileText,
  Film,
  Globe2,
  GraduationCap,
  Hash,
  Headphones,
  Image as ImageIcon,
  Languages,
  Lightbulb,
  Link2,
  MapPin,
  Mic,
  Music4,
  Notebook,
  PenLine,
  Presentation,
  Puzzle,
  Repeat,
  Rocket,
  Ruler,
  Sigma,
  Sparkles,
  Star,
  Target,
  Users,
  Video,
  Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { MaterialType } from './types'

/** Реестр иконок для тегов — храним в БД только имя. */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  Archive,
  AtSign,
  Award,
  BookMarked,
  BookOpen,
  Brain,
  Calculator,
  CalendarDays,
  ClipboardList,
  Clock,
  Code2,
  Compass,
  FlaskConical,
  Flame,
  FileText,
  Film,
  Globe2,
  GraduationCap,
  Hash,
  Headphones,
  ImageIcon,
  Languages,
  Lightbulb,
  Link2,
  MapPin,
  Mic,
  Music4,
  Notebook,
  PenLine,
  Presentation,
  Puzzle,
  Repeat,
  Rocket,
  Ruler,
  Sigma,
  Sparkles,
  Star,
  Target,
  Users,
  Video,
  Zap,
}

export const ICON_NAMES = Object.keys(ICON_REGISTRY)

export function iconByName(name?: string | null): LucideIcon {
  return (name && ICON_REGISTRY[name]) || Hash
}

/** Иконка типа материала */
export const MATERIAL_ICON: Record<MaterialType, LucideIcon> = {
  document: FileText,
  pdf: BookOpen,
  presentation: Presentation,
  video: Film,
  link: Link2,
  image: ImageIcon,
  audio: Headphones,
  note: Notebook,
  assignment: ClipboardList,
}
